Make Gen_all_checkscripts a proper reusable script
It still needs test but it uses and CL argument and find to configure
itself.

diff --git a/src/script/Gen_all_checkscripts b/src/script/Gen_all_checkscripts
--- a/src/script/Gen_all_checkscripts
+++ b/src/script/Gen_all_checkscripts
@@ -1,27 +1,48 @@
 #!/bin/bash
 
-cat <<EOF > template_script_tmp.in
+export ANALYZE_ROOT=""
+if [ $# -ne 1 ] ; then
+    echo "Where is the root of the analysis?"
+    echo "usage: $0 analyze_root"
+    exit 1
+else
+    export ANALYZE_ROOT="$1"
+fi
+
+export M0_U=$ANALYZE_ROOT/Mismatch_0/Unaligned
+export M1_U=$ANALYZE_ROOT/Mismatch_1/Unaligned
+if [ -d $M0_U ] && [ -d $M1_U ] ; then
+    echo "OK This seems standard"
+else
+    echo "Can't find $M0_U or $M1_U"
+    exit 1
+fi
+
+cat <<EOF > /tmp/template_script_tmp.in
 check_fastqs.ml \$ANALYZE_DIR/ > \$OUT_DIR/Check_FASTQs_\$NAME.txt
 
 EOF
 
-export ANALYZE_ROOT=/scratch/cgsb/sm4431/bclToFastq/D053MACXX/
-
 function make_one () {
-make_pbs_script.ml \
+    make_pbs_script.ml \
 	-var ANALYZE_DIR=$ANALYZE_ROOT/$1 \
-	-template template_script_tmp.in \
+	-template /tmp/template_script_tmp.in \
 	$2
 }
 
-make_one M0/Unaligned/Project_Carlton ChkFstq_M0Carlton
-make_one M1/Unaligned/Project_Carlton ChkFstq_M1Carlton
-make_one M0/Unaligned/Project_Gresham ChkFstq_M0Gresham
-make_one M1/Unaligned/Project_Gresham ChkFstq_M1Gresham
-make_one M0/Unaligned/Project_PhiX ChkFstq_M0PhiX
-make_one M1/Unaligned/Project_PhiX ChkFstq_M1PhiX
+PROJECTS_0=`find $M0_U -maxdepth 1  -name "Project_*" -type d`
+PROJECTS_1=`find $M1_U -maxdepth 1  -name "Project_*" -type d`
 
-make_one M0/Unaligned/Undetermined_indices ChkFstq_M0Undetermin
-make_one M1/Unaligned/Undetermined_indices ChkFstq_M1Undetermin
+echo $PROJECTS_0
+echo $PROJECTS_1
+
+for proj in $PROJECTS_0; do
+    NAME="CFM0`basename $proj`"
+    make_one $proj $NAME
+done
+for proj in $PROJECTS_1; do
+    NAME="CFM1`basename $proj`"
+    make_one $proj $NAME
+done
 
 
